language: php

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

matrix:
  include:
    - php: 5.3
      dist: precise

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
#  - nightly

notifications:
  email: wxxiong6@gmail.com

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php
script:
    - ./travis/run-tests.sh